### ISSUE TITLE
请问图中使用的ui是啥

### ISSUE THREAD

**Issue by EnderAvaritia** [izumiChan16/clash_ini2sing-box#1]

**Comment by izumiChan16** [comment]
http://yacd.haishan.me/
https://d.metacubex.one/#/conns
任选一个都可以

**Comment by EnderAvaritia** [comment]
> http://yacd.haishan.me/ https://d.metacubex.one/#/conns 任选一个都可以

谢谢

**Comment by EnderAvaritia** [comment]
这不是clash的面板吗？还能兼容singbox的？！

**Comment by izumiChan16** [comment]
@EnderAvaritia sing-box目前selector只能通过clash api实现

**Comment by EnderAvaritia** [comment]
> @EnderAvaritia sing-box目前selector只能通过clash api实现

我去看看咋用
