### ISSUE TITLE
使用此模板配合推荐的sing-box-subscribe项目，生成配置后闪退

### ISSUE THREAD

**Issue by bigoovip** [izumiChan16/clash_ini2sing-box#3]
为了测试，在下载本项目后，不更改任何内容，直接生成配置模板，然后使用此模板配合推荐的sing-box-subscribe项目，生成配置后在windows使用sing-box.exe官方客户端1.6.3版本闪退；
然后我使用sing-box-subscribe项目自带的模板，生成的配置，在windows使用sing-box.exe官方客户端1.6.3版本可以正常启动。
官方客户端1.7.0-alpha、1.6.1都试过，都是一样闪退。
日志设为error，输出为空。
不知道是哪里出问题了。

**Comment by izumiChan16** [comment]
你使用过sing-box check吗，按照你说的情况弄，我这里是正常运作的

**Comment by izumiChan16** [comment]
@yzbleaf 问题是，如果sing-box配置文件有问题，它应该是报错，而不是闪退。如果你应用程序闪退，真的是和配置文件有问题吗

**Comment by bigoovip** [comment]
> @yzbleaf 问题是，如果sing-box配置文件有问题，它应该是报错，而不是闪退。如果你应用程序闪退，真的是和配置文件有问题吗

谢谢，我用过sing-box check -c 配置文件，没有任何输出。
我现在也有点蒙，我看过配置文件，看起来应该是正常的，但就是会闪退，用subscribe项目的模板生成就正常，实在想不出哪里会出问题。
能问下你是用在windows吗？用的哪个版本客户端？

**Comment by izumiChan16** [comment]
@yzbleaf 也许你可以TG联系我，以下是我的好友链接Base64 Decode
aHR0cHM6Ly90Lm1lL2lpaWlpaXp4YzE2
